# Generated by Django 6.0.6 on 2026-06-18 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_alerte', models.FloatField(default=30.0, help_text='Taux de similarité (%) au-delà duquel un travail est signalé comme suspect.')),
                ('taille_ngramme', models.IntegerField(default=3, help_text='Taille des n-grammes utilisés pour la comparaison de texte.')),
                ('algorithme_par_defaut', models.CharField(choices=[('jaccard', 'Indice de Jaccard'), ('cosinus', 'Similarité cosinus')], default='jaccard', max_length=20)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du système',
                'verbose_name_plural': 'Configuration du système',
            },
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_plagiat', models.FloatField(default=0.0)),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('algorithme', models.CharField(choices=[('jaccard', 'Indice de Jaccard'), ('cosinus', 'Similarité cosinus')], default='jaccard', max_length=20)),
                ('enseignant', models.ForeignKey(limit_choices_to={'profil__role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_lancees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analyse',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-date_analyse'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('admin', 'Administrateur')], default='etudiant', max_length=20)),
                ('num_etudiant', models.CharField(blank=True, max_length=50, null=True)),
                ('filiere', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau_acces', models.IntegerField(blank=True, default=1, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='RapportPlagiat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('pourcentage', models.FloatField()),
                ('passages_similaires', models.JSONField(blank=True, default=list, help_text='Liste des passages similaires détectés : [{texte, source, score}, ...]')),
                ('contenu_resume', models.TextField(blank=True)),
                ('analyse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='detection.analyse')),
            ],
            options={
                'verbose_name': 'Rapport de plagiat',
                'verbose_name_plural': 'Rapports de plagiat',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='travaux/%Y/%m/')),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('extrait', 'Texte extrait'), ('analyse', 'Analysé'), ('erreur', 'Erreur')], default='en_attente', max_length=20)),
                ('texte_extrait', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(limit_choices_to={'profil__role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travail',
                'verbose_name_plural': 'Travaux',
                'ordering': ['-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='SourceSimilaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_similarite', models.FloatField()),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='detection.analyse')),
                ('travail_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cite_comme_source', to='detection.travail')),
            ],
            options={
                'verbose_name': 'Source similaire',
                'verbose_name_plural': 'Sources similaires',
                'ordering': ['-score_similarite'],
            },
        ),
        migrations.AddField(
            model_name='analyse',
            name='travail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='detection.travail'),
        ),
    ]
